"""
backend/database.py
====================
MongoDB Atlas data access layer for ABTD.
All database reads and writes go through this module.

Collections:
  - scans       : Full ABTD analysis results for URLs, files, processes
  - alerts      : Threat alerts generated by the Windows agent
  - settings    : User-configurable system settings
  - quarantine  : Quarantined file records

Connection: MongoDB Atlas (configured via MONGO_URI in .env)
"""

import sys
import ssl
from pathlib import Path
from datetime import datetime, timezone

# ── Python 3.14 TLS Compatibility Fix ─────────────────────────────────────────
# MongoDB Atlas rejects the TLS handshake with TLSV1_ALERT_INTERNAL_ERROR when
# using Python 3.14's newer OpenSSL cipher negotiation. We patch
# ssl.create_default_context to return a permissive context BEFORE pymongo
# imports ssl so that pymongo uses our context for all connections.
def _make_permissive_ssl_context(purpose=ssl.Purpose.SERVER_AUTH, *args, **kwargs):
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.check_hostname = False
    ctx.verify_mode    = ssl.CERT_NONE
    # OP_LEGACY_SERVER_CONNECT (Python 3.12+): allow legacy TLS cipher suites
    # that MongoDB Atlas clusters accept. This is the key fix for Python 3.14.
    if hasattr(ssl, "OP_LEGACY_SERVER_CONNECT"):
        ctx.options |= ssl.OP_LEGACY_SERVER_CONNECT  # type: ignore[attr-defined]
    return ctx

ssl.create_default_context = _make_permissive_ssl_context  # type: ignore[assignment]
# ─────────────────────────────────────────────────────────────────────────────

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config
from backend.logger import log_system

try:
    from pymongo import MongoClient, DESCENDING, ASCENDING
    from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError
    _PYMONGO_OK = True
except ImportError:
    _PYMONGO_OK = False
    log_system.warning("pymongo not installed — database features disabled")



class Database:
    """
    MongoDB Atlas data access object.

    All methods fail gracefully: if MongoDB is unavailable,
    they log a warning and return safe defaults so the rest
    of the system keeps running.
    """

    def __init__(self):
        self._client = None
        self._db     = None
        self._connected = False

    def connect(self) -> bool:
        """Establish connection to MongoDB Atlas. Returns True on success.

        Set MONGO_ENABLED=true in .env to enable database persistence.
        When disabled (default), the system runs in offline mode — all
        features work normally but scan history is not persisted.
        """
        if not _PYMONGO_OK:
            return False

        if not config.MONGO_ENABLED:
            log_system.info("MongoDB disabled (MONGO_ENABLED=false) — running in offline mode.")
            return False

        try:
            self._client = MongoClient(
                config.MONGO_URI,
                serverSelectionTimeoutMS=8000,
                connectTimeoutMS=8000,
                socketTimeoutMS=15000,
                tls=True,
                tlsAllowInvalidCertificates=True,
            )
            self._client.admin.command("ping")
            self._db = self._client[config.MONGO_DB]
            self._ensure_indexes()
            self._connected = True
            log_system.info(f"✓ MongoDB Atlas connected — DB: '{config.MONGO_DB}'")
            return True
        except Exception as e:
            log_system.warning(f"MongoDB connection failed: {e}")
            log_system.warning("System will run without database persistence.")
            self._connected = False
            return False



    def _ensure_indexes(self) -> None:
        """Create indexes for performance — covers both v1.0 and v2.0 collections."""
        try:
            scans = self._db[config.COLLECTIONS["scans"]]
            scans.create_index([("timestamp", DESCENDING)])
            scans.create_index([("classification", ASCENDING)])
            scans.create_index([("target_type", ASCENDING)])

            alerts = self._db[config.COLLECTIONS["alerts"]]
            alerts.create_index([("timestamp", DESCENDING)])
            alerts.create_index([("alert_type", ASCENDING)])
            alerts.create_index([("severity", ASCENDING)])

            # v2.0 Zero Trust indexes
            decisions = self._db[config.COLLECTIONS["access_decisions"]]
            decisions.create_index([("timestamp", DESCENDING)])
            decisions.create_index([("decision", ASCENDING)])
            decisions.create_index([("process_name", ASCENDING)])
            decisions.create_index([("overall_risk", DESCENDING)])

            incidents = self._db[config.COLLECTIONS["incidents"]]
            incidents.create_index([("created_at", DESCENDING)])
            incidents.create_index([("severity", ASCENDING)])
            incidents.create_index([("status", ASCENDING)])

            audit = self._db[config.COLLECTIONS["audit_log"]]
            audit.create_index([("timestamp", DESCENDING)])
            audit.create_index([("entity_type", ASCENDING)])

            assessments = self._db[config.COLLECTIONS["assessments"]]
            assessments.create_index([("assessed_at", DESCENDING)])

        except Exception as e:
            log_system.warning(f"Index creation warning: {e}")

    @property
    def is_connected(self) -> bool:
        return self._connected

    # ── Scan Operations ───────────────────────────────────────────────

    def log_scan(self, result: dict) -> str | None:
        """
        Persist a full ABTD analysis result.

        Args:
            result: The dict returned by engine.analyze_url / analyze_file / analyze_process

        Returns the inserted document ID (str) or None.
        """
        if not self._connected:
            return None
        try:
            doc = {**result, "logged_at": datetime.now(timezone.utc)}
            res = self._db[config.COLLECTIONS["scans"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_scan failed: {e}")
            return None

    def get_scan_history(
        self,
        page     : int = 1,
        page_size: int = None,
        target_type: str | None = None,
        classification: str | None = None,
    ) -> dict:
        """Return paginated scan history."""
        if not self._connected:
            return {"items": [], "total": 0, "page": page, "pages": 0}

        page_size = page_size or config.PAGE_SIZE
        skip = (page - 1) * page_size

        query = {}
        if target_type:
            query["target_type"] = target_type
        if classification:
            query["classification"] = classification.upper()

        try:
            col   = self._db[config.COLLECTIONS["scans"]]
            total = col.count_documents(query)
            docs  = list(
                col.find(query, {"_id": 0})
                   .sort("timestamp", DESCENDING)
                   .skip(skip)
                   .limit(page_size)
            )
            return {
                "items" : docs,
                "total" : total,
                "page"  : page,
                "pages" : (total + page_size - 1) // page_size,
            }
        except Exception as e:
            log_system.error(f"get_scan_history failed: {e}")
            return {"items": [], "total": 0, "page": page, "pages": 0}

    def get_stats(self) -> dict:
        """Return dashboard statistics."""
        if not self._connected:
            return self._empty_stats()

        try:
            scans_col  = self._db[config.COLLECTIONS["scans"]]
            alerts_col = self._db[config.COLLECTIONS["alerts"]]

            total_scans  = scans_col.count_documents({})
            total_threats= scans_col.count_documents({"classification": {"$in": ["MALICIOUS", "CRITICAL"]}})
            total_sus    = scans_col.count_documents({"classification": "SUSPICIOUS"})
            total_safe   = scans_col.count_documents({"classification": "SAFE"})
            total_alerts = alerts_col.count_documents({})

            # Recent 5 threats
            recent_threats = list(
                scans_col.find(
                    {"classification": {"$in": ["MALICIOUS", "CRITICAL", "SUSPICIOUS"]}},
                    {"_id": 0, "url": 1, "file_path": 1, "process_name": 1,
                     "classification": 1, "threat_score": 1, "timestamp": 1,
                     "target_type": 1, "color": 1, "icon": 1}
                ).sort("timestamp", DESCENDING).limit(5)
            )

            return {
                "total_scans"  : total_scans,
                "total_threats": total_threats,
                "suspicious"   : total_sus,
                "safe"         : total_safe,
                "total_alerts" : total_alerts,
                "threat_rate"  : round(total_threats / max(total_scans, 1) * 100, 1),
                "recent_threats": recent_threats,
            }
        except Exception as e:
            log_system.error(f"get_stats failed: {e}")
            return self._empty_stats()

    def _empty_stats(self) -> dict:
        return {
            "total_scans": 0, "total_threats": 0,
            "suspicious": 0, "safe": 0,
            "total_alerts": 0, "threat_rate": 0.0,
            "recent_threats": [],
        }

    # ── Alert Operations ──────────────────────────────────────────────

    def log_alert(
        self,
        alert_type   : str,
        severity     : str,
        title        : str,
        description  : str,
        source       : str = "agent",
        details      : dict | None = None,
    ) -> str | None:
        """Persist a threat alert from the Windows agent."""
        if not self._connected:
            return None
        try:
            doc = {
                "alert_type" : alert_type,
                "severity"   : severity,    # LOW / MEDIUM / HIGH / CRITICAL
                "title"      : title,
                "description": description,
                "source"     : source,
                "details"    : details or {},
                "timestamp"  : datetime.now(timezone.utc),
                "acknowledged": False,
            }
            res = self._db[config.COLLECTIONS["alerts"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_alert failed: {e}")
            return None

    def get_alerts(
        self,
        alert_type : str | None = None,
        severity   : str | None = None,
        limit      : int = 50,
    ) -> list:
        """Return recent alerts, optionally filtered."""
        if not self._connected:
            return []
        try:
            query = {}
            if alert_type:
                query["alert_type"] = alert_type
            if severity:
                query["severity"] = severity.upper()

            return list(
                self._db[config.COLLECTIONS["alerts"]]
                .find(query, {"_id": 0})
                .sort("timestamp", DESCENDING)
                .limit(limit)
            )
        except Exception as e:
            log_system.error(f"get_alerts failed: {e}")
            return []

    def get_threat_timeline(self, days: int = 7) -> list:
        """Return daily threat counts for the last N days."""
        if not self._connected:
            return []
        try:
            from datetime import timedelta
            since = datetime.now(timezone.utc) - timedelta(days=days)
            pipeline = [
                {"$match": {
                    "timestamp": {"$gte": since.isoformat()},
                    "classification": {"$in": ["MALICIOUS", "CRITICAL", "SUSPICIOUS"]},
                }},
                {"$group": {
                    "_id": {"$substr": ["$timestamp", 0, 10]},
                    "count": {"$sum": 1},
                }},
                {"$sort": {"_id": 1}},
            ]
            return list(self._db[config.COLLECTIONS["scans"]].aggregate(pipeline))
        except Exception as e:
            log_system.error(f"get_threat_timeline failed: {e}")
            return []

    # ── Quarantine Operations ─────────────────────────────────────────

    def add_quarantine(self, file_path: str, reason: str, threat_score: int) -> str | None:
        """Record a quarantined file."""
        if not self._connected:
            return None
        try:
            doc = {
                "file_path"  : file_path,
                "reason"     : reason,
                "threat_score": threat_score,
                "quarantined_at": datetime.now(timezone.utc),
                "restored"   : False,
            }
            res = self._db[config.COLLECTIONS["quarantine"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"add_quarantine failed: {e}")
            return None

    def get_quarantine_list(self) -> list:
        if not self._connected:
            return []
        try:
            return list(
                self._db[config.COLLECTIONS["quarantine"]]
                .find({"restored": False}, {"_id": 0})
                .sort("quarantined_at", DESCENDING)
                .limit(100)
            )
        except Exception as e:
            log_system.error(f"get_quarantine_list failed: {e}")
            return []

    # ── Settings ──────────────────────────────────────────────────────

    def get_settings(self) -> dict:
        """Return current system settings from DB (or defaults)."""
        defaults = {
            "agent_enabled"       : config.AGENT_ENABLED,
            "scan_interval"       : config.AGENT_SCAN_INTERVAL_S,
            "gemini_enabled"      : config.GEMINI_ENABLED,
            "notifications"       : True,
            "auto_quarantine"     : False,
            "threat_threshold"    : config.THRESHOLDS["suspicious"],
            "watched_dirs"        : config.WATCHED_DIRS,
        }
        if not self._connected:
            return defaults
        try:
            doc = self._db[config.COLLECTIONS["settings"]].find_one({}, {"_id": 0})
            return doc if doc else defaults
        except Exception:
            return defaults

    def save_settings(self, settings: dict) -> bool:
        if not self._connected:
            return False
        try:
            self._db[config.COLLECTIONS["settings"]].replace_one(
                {}, settings, upsert=True
            )
            return True
        except Exception as e:
            log_system.error(f"save_settings failed: {e}")
            return False


    # ── Zero Trust: Access Decisions ──────────────────────────────────────────

    def log_access_decision(self, decision: dict) -> str | None:
        """
        Persist a Zero Trust access decision.
        Called by the AccessController after every evaluation.
        """
        if not self._connected:
            return None
        try:
            from datetime import datetime, timezone
            doc = {**decision, "logged_at": datetime.now(timezone.utc)}
            # Trim large nested fields to avoid exceeding MongoDB document limit
            for key in ("signals", "risk_calculation", "process"):
                if key in doc and isinstance(doc[key], dict):
                    # Keep but don't store the full nested history
                    pass
            res = self._db[config.COLLECTIONS["access_decisions"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_access_decision failed: {e}")
            return None

    def get_access_decisions(
        self,
        page        : int = 1,
        page_size   : int = None,
        decision    : str | None = None,
        event_type  : str | None = None,
    ) -> dict:
        """Return paginated Zero Trust access decisions."""
        if not self._connected:
            return {"items": [], "total": 0, "page": page, "pages": 0}
        page_size = page_size or config.PAGE_SIZE
        skip = (page - 1) * page_size
        query = {}
        if decision:
            query["decision"] = decision.upper()
        if event_type:
            query["event_type"] = event_type
        try:
            col   = self._db[config.COLLECTIONS["access_decisions"]]
            total = col.count_documents(query)
            docs  = list(
                col.find(query, {"_id": 0})
                   .sort("timestamp", DESCENDING)
                   .skip(skip)
                   .limit(page_size)
            )
            return {
                "items" : docs,
                "total" : total,
                "page"  : page,
                "pages" : (total + page_size - 1) // page_size,
            }
        except Exception as e:
            log_system.error(f"get_access_decisions failed: {e}")
            return {"items": [], "total": 0, "page": page, "pages": 0}

    def get_decision_stats(self) -> dict:
        """Return aggregate decision statistics for dashboard."""
        if not self._connected:
            return {"allow": 0, "monitor": 0, "restrict": 0, "block": 0, "total": 0}
        try:
            col      = self._db[config.COLLECTIONS["access_decisions"]]
            pipeline = [
                {"$group": {"_id": "$decision", "count": {"$sum": 1}}}
            ]
            results = {r["_id"]: r["count"] for r in col.aggregate(pipeline)}
            total   = sum(results.values())
            return {
                "allow"    : results.get("ALLOW", 0),
                "monitor"  : results.get("MONITOR", 0),
                "restrict" : results.get("RESTRICT", 0) + results.get("CHALLENGE", 0),
                "block"    : results.get("BLOCK", 0) + results.get("QUARANTINE", 0),
                "total"    : total,
                "by_type"  : results,
            }
        except Exception as e:
            log_system.error(f"get_decision_stats failed: {e}")
            return {"allow": 0, "monitor": 0, "restrict": 0, "block": 0, "total": 0}

    # ── Zero Trust: Incidents ─────────────────────────────────────────────────

    def log_incident(self, incident: dict) -> str | None:
        """Persist a correlated security incident."""
        if not self._connected:
            return None
        try:
            from datetime import datetime, timezone
            doc = {**incident, "logged_at": datetime.now(timezone.utc)}
            res = self._db[config.COLLECTIONS["incidents"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_incident failed: {e}")
            return None

    def get_incidents(
        self,
        status  : str | None = None,
        severity: str | None = None,
        limit   : int = 50,
    ) -> list:
        """Return recent incidents from database."""
        if not self._connected:
            return []
        try:
            query = {}
            if status:
                query["status"]   = status.upper()
            if severity:
                query["severity"] = severity.upper()
            return list(
                self._db[config.COLLECTIONS["incidents"]]
                .find(query, {"_id": 0})
                .sort("created_at", DESCENDING)
                .limit(limit)
            )
        except Exception as e:
            log_system.error(f"get_incidents failed: {e}")
            return []

    # ── Zero Trust: Device Posture ────────────────────────────────────────────

    def save_device_posture(self, posture: dict) -> str | None:
        """Save a device trust assessment snapshot."""
        if not self._connected:
            return None
        try:
            from datetime import datetime, timezone
            doc = {**posture, "logged_at": datetime.now(timezone.utc)}
            res = self._db[config.COLLECTIONS["device_posture"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"save_device_posture failed: {e}")
            return None

    def get_device_posture_history(self, limit: int = 10) -> list:
        """Return recent device posture assessments."""
        if not self._connected:
            return []
        try:
            return list(
                self._db[config.COLLECTIONS["device_posture"]]
                .find({}, {"_id": 0})
                .sort("logged_at", DESCENDING)
                .limit(limit)
            )
        except Exception as e:
            log_system.error(f"get_device_posture_history failed: {e}")
            return []

    # ── Zero Trust: Security Assessments ─────────────────────────────────────

    def save_assessment(self, assessment: dict) -> str | None:
        """Save a full security assessment result."""
        if not self._connected:
            return None
        try:
            from datetime import datetime, timezone
            doc = {**assessment, "saved_at": datetime.now(timezone.utc)}
            res = self._db[config.COLLECTIONS["assessments"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"save_assessment failed: {e}")
            return None

    def get_latest_assessment(self) -> dict | None:
        """Return the most recent security assessment."""
        if not self._connected:
            return None
        try:
            doc = (
                self._db[config.COLLECTIONS["assessments"]]
                .find_one({}, {"_id": 0}, sort=[("saved_at", DESCENDING)])
            )
            return doc
        except Exception as e:
            log_system.error(f"get_latest_assessment failed: {e}")
            return None

    def get_assessment_history(self, limit: int = 10) -> list:
        """Return assessment history."""
        if not self._connected:
            return []
        try:
            return list(
                self._db[config.COLLECTIONS["assessments"]]
                .find({}, {"_id": 0, "findings": 0})
                .sort("saved_at", DESCENDING)
                .limit(limit)
            )
        except Exception as e:
            log_system.error(f"get_assessment_history failed: {e}")
            return []

    # ── Audit Log ─────────────────────────────────────────────────────────────

    def write_audit_log(
        self,
        entity_type : str,
        entity_id   : str,
        action      : str,
        outcome     : str,
        details     : dict | None = None,
    ) -> str | None:
        """Write an immutable audit log entry."""
        if not self._connected:
            return None
        try:
            from datetime import datetime, timezone
            doc = {
                "entity_type": entity_type,
                "entity_id"  : entity_id,
                "action"     : action,
                "outcome"    : outcome,
                "details"    : details or {},
                "timestamp"  : datetime.now(timezone.utc),
            }
            res = self._db[config.COLLECTIONS["audit_log"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"write_audit_log failed: {e}")
            return None


# Singleton — imported by all routes and the agent
db = Database()
