"""
backend/database.py
====================
MongoDB Atlas data access layer for ABTD.
All database reads and writes go through this module.

Collections:
  - scans       : Full ABTD analysis results for URLs, files, processes
  - alerts      : Threat alerts generated by the Windows agent
  - settings    : User-configurable system settings
  - quarantine  : Quarantined file records

Connection: MongoDB Atlas (configured via MONGO_URI in .env)
"""

import sys
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import config
from backend.logger import log_system

try:
    from pymongo import MongoClient, DESCENDING, ASCENDING
    from pymongo.errors import ConnectionFailure, ServerSelectionTimeoutError
    _PYMONGO_OK = True
except ImportError:
    _PYMONGO_OK = False
    log_system.warning("pymongo not installed — database features disabled")


class Database:
    """
    MongoDB Atlas data access object.

    All methods fail gracefully: if MongoDB is unavailable,
    they log a warning and return safe defaults so the rest
    of the system keeps running.
    """

    def __init__(self):
        self._client = None
        self._db     = None
        self._connected = False

    def connect(self) -> bool:
        """Establish connection to MongoDB Atlas. Returns True on success."""
        if not _PYMONGO_OK:
            return False

        try:
            self._client = MongoClient(
                config.MONGO_URI,
                serverSelectionTimeoutMS=5000,
                connectTimeoutMS=5000,
                socketTimeoutMS=10000,
                tls=True,
            )
            # Trigger actual connection
            self._client.admin.command("ping")
            self._db = self._client[config.MONGO_DB]

            # Create indexes
            self._ensure_indexes()
            self._connected = True
            log_system.info(f"✓ MongoDB Atlas connected — DB: '{config.MONGO_DB}'")
            return True
        except Exception as e:
            log_system.warning(f"MongoDB connection failed: {e}")
            log_system.warning("System will run without database persistence.")
            self._connected = False
            return False

    def _ensure_indexes(self) -> None:
        """Create indexes for performance."""
        try:
            scans = self._db[config.COLLECTIONS["scans"]]
            scans.create_index([("timestamp", DESCENDING)])
            scans.create_index([("classification", ASCENDING)])
            scans.create_index([("target_type", ASCENDING)])

            alerts = self._db[config.COLLECTIONS["alerts"]]
            alerts.create_index([("timestamp", DESCENDING)])
            alerts.create_index([("alert_type", ASCENDING)])
            alerts.create_index([("severity", ASCENDING)])
        except Exception as e:
            log_system.warning(f"Index creation warning: {e}")

    @property
    def is_connected(self) -> bool:
        return self._connected

    # ── Scan Operations ───────────────────────────────────────────────

    def log_scan(self, result: dict) -> str | None:
        """
        Persist a full ABTD analysis result.

        Args:
            result: The dict returned by engine.analyze_url / analyze_file / analyze_process

        Returns the inserted document ID (str) or None.
        """
        if not self._connected:
            return None
        try:
            doc = {**result, "logged_at": datetime.now(timezone.utc)}
            res = self._db[config.COLLECTIONS["scans"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_scan failed: {e}")
            return None

    def get_scan_history(
        self,
        page     : int = 1,
        page_size: int = None,
        target_type: str | None = None,
        classification: str | None = None,
    ) -> dict:
        """Return paginated scan history."""
        if not self._connected:
            return {"items": [], "total": 0, "page": page, "pages": 0}

        page_size = page_size or config.PAGE_SIZE
        skip = (page - 1) * page_size

        query = {}
        if target_type:
            query["target_type"] = target_type
        if classification:
            query["classification"] = classification.upper()

        try:
            col   = self._db[config.COLLECTIONS["scans"]]
            total = col.count_documents(query)
            docs  = list(
                col.find(query, {"_id": 0})
                   .sort("timestamp", DESCENDING)
                   .skip(skip)
                   .limit(page_size)
            )
            return {
                "items" : docs,
                "total" : total,
                "page"  : page,
                "pages" : (total + page_size - 1) // page_size,
            }
        except Exception as e:
            log_system.error(f"get_scan_history failed: {e}")
            return {"items": [], "total": 0, "page": page, "pages": 0}

    def get_stats(self) -> dict:
        """Return dashboard statistics."""
        if not self._connected:
            return self._empty_stats()

        try:
            scans_col  = self._db[config.COLLECTIONS["scans"]]
            alerts_col = self._db[config.COLLECTIONS["alerts"]]

            total_scans  = scans_col.count_documents({})
            total_threats= scans_col.count_documents({"classification": {"$in": ["MALICIOUS", "CRITICAL"]}})
            total_sus    = scans_col.count_documents({"classification": "SUSPICIOUS"})
            total_safe   = scans_col.count_documents({"classification": "SAFE"})
            total_alerts = alerts_col.count_documents({})

            # Recent 5 threats
            recent_threats = list(
                scans_col.find(
                    {"classification": {"$in": ["MALICIOUS", "CRITICAL", "SUSPICIOUS"]}},
                    {"_id": 0, "url": 1, "file_path": 1, "process_name": 1,
                     "classification": 1, "threat_score": 1, "timestamp": 1,
                     "target_type": 1, "color": 1, "icon": 1}
                ).sort("timestamp", DESCENDING).limit(5)
            )

            return {
                "total_scans"  : total_scans,
                "total_threats": total_threats,
                "suspicious"   : total_sus,
                "safe"         : total_safe,
                "total_alerts" : total_alerts,
                "threat_rate"  : round(total_threats / max(total_scans, 1) * 100, 1),
                "recent_threats": recent_threats,
            }
        except Exception as e:
            log_system.error(f"get_stats failed: {e}")
            return self._empty_stats()

    def _empty_stats(self) -> dict:
        return {
            "total_scans": 0, "total_threats": 0,
            "suspicious": 0, "safe": 0,
            "total_alerts": 0, "threat_rate": 0.0,
            "recent_threats": [],
        }

    # ── Alert Operations ──────────────────────────────────────────────

    def log_alert(
        self,
        alert_type   : str,
        severity     : str,
        title        : str,
        description  : str,
        source       : str = "agent",
        details      : dict | None = None,
    ) -> str | None:
        """Persist a threat alert from the Windows agent."""
        if not self._connected:
            return None
        try:
            doc = {
                "alert_type" : alert_type,
                "severity"   : severity,    # LOW / MEDIUM / HIGH / CRITICAL
                "title"      : title,
                "description": description,
                "source"     : source,
                "details"    : details or {},
                "timestamp"  : datetime.now(timezone.utc),
                "acknowledged": False,
            }
            res = self._db[config.COLLECTIONS["alerts"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"log_alert failed: {e}")
            return None

    def get_alerts(
        self,
        alert_type : str | None = None,
        severity   : str | None = None,
        limit      : int = 50,
    ) -> list:
        """Return recent alerts, optionally filtered."""
        if not self._connected:
            return []
        try:
            query = {}
            if alert_type:
                query["alert_type"] = alert_type
            if severity:
                query["severity"] = severity.upper()

            return list(
                self._db[config.COLLECTIONS["alerts"]]
                .find(query, {"_id": 0})
                .sort("timestamp", DESCENDING)
                .limit(limit)
            )
        except Exception as e:
            log_system.error(f"get_alerts failed: {e}")
            return []

    def get_threat_timeline(self, days: int = 7) -> list:
        """Return daily threat counts for the last N days."""
        if not self._connected:
            return []
        try:
            from datetime import timedelta
            since = datetime.now(timezone.utc) - timedelta(days=days)
            pipeline = [
                {"$match": {
                    "timestamp": {"$gte": since.isoformat()},
                    "classification": {"$in": ["MALICIOUS", "CRITICAL", "SUSPICIOUS"]},
                }},
                {"$group": {
                    "_id": {"$substr": ["$timestamp", 0, 10]},
                    "count": {"$sum": 1},
                }},
                {"$sort": {"_id": 1}},
            ]
            return list(self._db[config.COLLECTIONS["scans"]].aggregate(pipeline))
        except Exception as e:
            log_system.error(f"get_threat_timeline failed: {e}")
            return []

    # ── Quarantine Operations ─────────────────────────────────────────

    def add_quarantine(self, file_path: str, reason: str, threat_score: int) -> str | None:
        """Record a quarantined file."""
        if not self._connected:
            return None
        try:
            doc = {
                "file_path"  : file_path,
                "reason"     : reason,
                "threat_score": threat_score,
                "quarantined_at": datetime.now(timezone.utc),
                "restored"   : False,
            }
            res = self._db[config.COLLECTIONS["quarantine"]].insert_one(doc)
            return str(res.inserted_id)
        except Exception as e:
            log_system.error(f"add_quarantine failed: {e}")
            return None

    def get_quarantine_list(self) -> list:
        if not self._connected:
            return []
        try:
            return list(
                self._db[config.COLLECTIONS["quarantine"]]
                .find({"restored": False}, {"_id": 0})
                .sort("quarantined_at", DESCENDING)
                .limit(100)
            )
        except Exception as e:
            log_system.error(f"get_quarantine_list failed: {e}")
            return []

    # ── Settings ──────────────────────────────────────────────────────

    def get_settings(self) -> dict:
        """Return current system settings from DB (or defaults)."""
        defaults = {
            "agent_enabled"       : config.AGENT_ENABLED,
            "scan_interval"       : config.AGENT_SCAN_INTERVAL_S,
            "gemini_enabled"      : config.GEMINI_ENABLED,
            "notifications"       : True,
            "auto_quarantine"     : False,
            "threat_threshold"    : config.THRESHOLDS["suspicious"],
            "watched_dirs"        : config.WATCHED_DIRS,
        }
        if not self._connected:
            return defaults
        try:
            doc = self._db[config.COLLECTIONS["settings"]].find_one({}, {"_id": 0})
            return doc if doc else defaults
        except Exception:
            return defaults

    def save_settings(self, settings: dict) -> bool:
        if not self._connected:
            return False
        try:
            self._db[config.COLLECTIONS["settings"]].replace_one(
                {}, settings, upsert=True
            )
            return True
        except Exception as e:
            log_system.error(f"save_settings failed: {e}")
            return False


# Singleton — imported by all routes and the agent
db = Database()
